package exceptions.users

class UserAlreadyExistsException: Exception("Пользователь уже существует")